# Generated by Django 4.1.7 on 2023-02-17 12:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_alter_course_thumbnail_alter_lesson_video_reviews'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('user', 'lesson')},
        ),
    ]
